# Generated by Django 2.1.2 on 2018-12-17 15:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(default='uploads/profile_pic/blank-profile-picture-973460_640.png', upload_to=accounts.models.unique_file_name),
        ),
    ]
