# Generated by Django 2.1.2 on 2018-12-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20181213_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmessage',
            name='is_read',
        ),
    ]
